package org.example.db.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.example.db.DaoBase;
import org.example.db.EntityBase;
import org.example.db.HsqlUnitOfWork;
import org.example.list.Attack;
import org.example.list.Octo;

public class HsqlOctoDao extends HsqlDaoBase<Octo> implements OctoDao{

	
	public HsqlOctoDao(HsqlUnitOfWork uow) {
		super(uow);
	}

	public void setAddresses(Octo c) {
		
	}

	public void setOrders(Octo c) {
		
	}

	@Override
	protected void setUpdateQuery(Octo ent) throws SQLException {

		update.setString(1, ent.getName());
		update.setString(2, ent.getSurname());
		update.setString(3, ent.getEmail());
		update.setString(4, ent.getNumber());
		update.setInt(5, ent.getId());
		
	}

	@Override
	protected Octo build(ResultSet rs) throws SQLException {

		Octo c = new Octo();
		c.setEmail(rs.getString("email"));
		c.setName(rs.getString("name"));
		c.setSurname(rs.getString("surname"));
		c.setNumber(rs.getString("number"));
		c.setId(rs.getInt("id"));
		return c;
	}

	@Override
	protected void setInsertQuery(Octo ent) throws SQLException {
		insert.setString(1, ent.getName());
		insert.setString(2, ent.getSurname());
		insert.setString(3, ent.getEmail());
		insert.setString(4, ent.getNumber());
		
		
	}

	@Override
	protected String getTableName() {
		return "octo";
	}

	@Override
	protected String getCreateQuery() {
		return "CREATE TABLE Octo("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(50),"
				+ "surname VARCHAR(50),"
				+ "email VARCHAR(50),"
				+ "number VARCHAR(50)"
				+ ")";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into octo(name,surname,email,number) values (?,?,?,?)";
	}

	@Override
	protected String getUpdateQuery() {
		return "update octo set"
				+ "(name,surname,email,number)=(?,?,?,?)"
				+ "where id=?";
	}

	public void setAttacks(Octo c) {
		// TODO Auto-generated method stub
		
	}

}
