package org.example.db.dao;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.example.db.DaoBase;
import org.example.db.EntityBase;
import org.example.db.HsqlUnitOfWork;
import org.example.list.Attack;
import org.example.list.Character;
import org.example.list.Octo;

public class HsqlAttackDao extends HsqlDaoBase<Attack>  implements AttackDao{
	
	public HsqlAttackDao(HsqlUnitOfWork uowa) {
		super(uowa);
	}
public void setAttacks(Attack a) {
		
	}

	public void setCharacters(Character ch) {
		
	}

	
	protected void setUpdateQuery(Attack ent) throws SQLException {

		update.setString(1, ent.getCity());
		update.setString(2, ent.getStreet());
		update.setString(3, ent.getPostalCode());
		update.setInt(4, ent.getLocalNumber());
		update.setString(5, ent.getHouseNumber());
		update.setInt(6, ent.getId());
		
	}

	protected Attack build(ResultSet rs) throws SQLException {

		Attack a = new Attack();
		a.setCity(rs.getString("city"));
		a.setStreet(rs.getString("street"));
		a.setPostalCode(rs.getString("postal code"));
		a.setLocalNumber(rs.getInt("local number"));
		a.setHouseNumber(rs.getString("house number"));

		a.setId(rs.getInt("id"));
		return a;
	}

	protected void setInsertQuery(Attack ent) throws SQLException {
		insert.setString(1, ent.getCity());
		insert.setString(2, ent.getStreet());
		insert.setString(3, ent.getPostalCode());
		insert.setInt(4, ent.getLocalNumber());
		insert.setString(5, ent.getHouseNumber());
		insert.setInt(6, ent.getId());
		
	}

	protected String getTableName() {
		return "attack";
	}

	protected String getCreateQuery() {
		return "CREATE TABLE Octo("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "city VARCHAR(50),"
				+ "street VARCHAR(50),"
				+ "local number int(50),"
				+ "house number VARCHAR(50),"
				+ "postal code VARCHAR(10)"
				+ ")";
	}

	protected String getInsertQuery() {
		return "insert into attack(city, street, local number,house number, postal code) values (?,?,?,?,?)";
	}

	protected String getUpdateQuery() {
		return "update attack set"
				+ "(city, street, local number,house number, postal code)=(?,?,?,?,?)"
				+ "where id=?";
	}

	

	@Override
	public Attack get(int id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Attack> getAll() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void persistAdd(EntityBase ent) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void persistDelete(EntityBase ent) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void persistUpdate(EntityBase ent) {
		// TODO Auto-generated method stub
		
	}


	public List<Attack> getAttackByOctoId(int id) {
		// TODO Auto-generated method stub
		return null;
	}}